#!/bin/bash
#
# srctool
#
# Useful for managing srcds. Currently supports only Counter-Strike Souce.
# -jimbru

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MMSOURCE="mmsource-1.8.7-linux.tar.gz"
SOURCEMOD="sourcemod-1.4.2-linux.tar.gz"

cmd_help() {
  print_usage
  echo ""
  echo "srctool commands:"
  echo "  help            Prints help."
  echo "  install <dir>   Installs a srcds instance to the specificed directory."
  echo ""
}

cmd_install() {
  INSTALL_PATH=$1
  : ${INSTALL_PATH:="."}

  SRCDS_PATH=$INSTALL_PATH/srcds
  mkdir -p $SRCDS_PATH

  echo -e "\n>> Installing srcds into $SRCDS_PATH ..."
  cmd_install_srcds $SRCDS_PATH

  echo -e "\n>> Installing Metamod:Source ..."
  cmd_install_mmsource $SRCDS_PATH

  echo -e "\n>> Installing Sourcemod ..."
  cmd_install_sourcemod $SRCDS_PATH

  print_done
}

cmd_install_srcds() {
  echo yes | $SCRIPT_PATH/hldsupdatetool.bin > /dev/null
  if [[ $? != 0 ]]
  then
    print_error "Hldsupdatetool.bin exited abnormally."
    exit 1
  fi

  mv readme.txt $1/srcds_readme.txt
  mv steam $1/

  RETURN=1
  INDEX=0
  RETRY=5
  while [[ $RETURN != 0 && $INDEX < $RETRY ]]
  do
    $1/steam -command update -game "Counter-Strike Source" -dir $1
    RETURN=$?
    ((++INDEX))
  done
  if [[ $INDEX == $RETRY ]]
  then
    print_error "Steam failed after $RETRY retries."
    exit 1
  fi
}

cmd_install_mmsource() {
  mkdir tmp
  tar -zxf $MMSOURCE -C tmp/
  cp -Rp tmp/addons $1/cstrike/
  cp metamod.vdf $1/cstrike/addons/
  rm -rf tmp
}

cmd_install_sourcemod() {
  mkdir tmp
  tar -zxf $SOURCEMOD -C tmp/
  cp -Rp tmp/addons $1/cstrike/
  cp -Rp tmp/cfg $1/cstrike/
  rm -rf tmp
}

print_done() {
  GREEN='\e[0;32m'
  ENDCOLOR='\e[0m'
  echo -e "[ ${GREEN}DONE${ENDCOLOR} ]"
}

print_error() {
  RED='\e[0;31m'
  ENDCOLOR='\e[0m'
  echo -e "[ ${RED}ERROR${ENDCOLOR} ] $1"
}

print_usage() {
  echo "Usage: $0 <command> [-opts] [<args>]"
}

# -----

if [[ $# < 1 ]]
then
  print_usage
  exit 1
fi

ACTION=$1
shift
case $ACTION in
  install ) cmd_install $@ ;;
  help    ) cmd_help ;;
  *       ) echo "Unknown action. Type '$0 help' for help. Exiting..." ;;
esac
exit 0
